name 'cek-ssh'
version '1.0.1'

author ''
license ''
project_page ''
source ''
summary 'Puppet ssh Module'
description 'Module for configuring ssh.'
dependency 'puppetlabs/stdlib', '>=2.2.1'
dependency 'cek/fstdlib', '~0.0.3'
